inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "config/application.rb"
    - "Guardfile"
    - "db/schema.rb"
    - "node_modules/**/*"
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Minitest/MultipleAssertions:
  Exclude:
    - "test/integration/**/*"

Naming/PredicateName:
  Exclude:
    - "test/test_helper.rb"

Rails/HelperInstanceVariable:
  Exclude:
    - "app/helpers/sessions_helper.rb"

Rails/SkipsModelValidations:
  Exclude:
    - "test/**/*"
